feature:
  cycles_to_keep: 98
  diff_base: 8
  max_cycle_index: 98
  name: VoltageCapacityMatrixFeatureExtractor
feature_transformation:
  name: ZScoreDataTransformation
label:
  name: RULLabelAnnotator
label_transformation:
  name: SequentialDataTransformation
  transformations:
  - name: LogScaleDataTransformation
  - name: ZScoreDataTransformation
model:
  name: RidgeRULPredictor
train_test_split:
  cell_data_path: data/processed/HUST/final_5_12
  name: HUSTTrainTestSplitter
