feature:
  diff_base: 9
  max_cycle_index: 99
  name: VoltageCapacityMatrixFeatureExtractor
  use_precalculated_qdlin: true
label:
  name: RULLabelAnnotator
label_transformation:
  name: SequentialDataTransformation
  transformations:
  - name: LogScaleDataTransformation
  - name: ZScoreDataTransformation
model:
  batch_size: 64
  channels: 56
  epochs: 200
  evaluate_freq: 100
  in_channels: 1
  input_height: 100
  input_width: 1000
  name: CNNRULPredictor
train_test_split:
  cell_data_path: data/processed/HUST/final_5_12
  name: HUSTTrainTestSplitter
