model:
  name: 'CNNRULPredictor'
  in_channels: 1
  channels: 56
  input_height: 100
  input_width: 1000
  epochs: 100
  batch_size: 224
  evaluate_freq: 100
train_test_split:
  name: 'HUSTTrainTestSplitter'
  cell_data_path: 'data/processed/HUST'
feature:
  interp_dim: 800
  name: 'VoltageCapacityMatrixFeatureExtractor'
  diff_base: 9
  max_cycle_index: 99
  use_precalculated_qdlin: True
label:
  name: 'RULLabelAnnotator'
label_transformation:
  name: 'SequentialDataTransformation'
  transformations:
    - name: 'LogScaleDataTransformation'
    - name: 'ZScoreDataTransformation'
# 'cnn': {'best_params': {'channels': 56, 'epochs': 100, 'batch_size': 224, 'interp_dim': 800},
