model:
  name: 'MLPRULPredictor'
  in_channels: 1
  channels: 24
  input_height: 1
  input_width: 1000
  epochs: 800
  batch_size: 96
  evaluate_freq: 100
train_test_split:
  name: 'HUSTTrainTestSplitter'
  cell_data_path: 'data/processed/HUST'
feature:
  interp_dim: 600
  name: 'VoltageCapacityMatrixFeatureExtractor'
  diff_base: 9
  cycles_to_keep: 99
  max_cycle_index: 99
  use_precalculated_qdlin: True
label:
  name: 'RULLabelAnnotator'
label_transformation:
  name: 'SequentialDataTransformation'
  transformations:
    - name: 'LogScaleDataTransformation'
    - name: 'ZScoreDataTransformation'
# 'mlp': {'best_params': {'channels': 24, 'epochs': 800, 'batch_size': 96, 'interp_dim': 600}, 'best_test_loss': 15.654444694519043},
