model:
  name: 'LSTMRULPredictor'
  in_channels: 1
  channels: 48
  input_height: 100
  input_width: 1000
  epochs: 1100
  batch_size: 160
  evaluate_freq: 100
train_test_split:
  name: 'HUSTTrainTestSplitter'
  cell_data_path: 'data/processed/HUST'
feature:
  interp_dim: 600
  name: 'VoltageCapacityMatrixFeatureExtractor'
  diff_base: 9
  max_cycle_index: 99
  use_precalculated_qdlin: True
label:
  name: 'RULLabelAnnotator'
label_transformation:
  name: 'SequentialDataTransformation'
  transformations:
    - name: 'LogScaleDataTransformation'
    - name: 'ZScoreDataTransformation'

    # 'lstm': {'best_params': {'channels': 48, 'epochs': 1100, 'batch_size': 160, 'interp_dim': 600}, 'best_test_loss': 18.378562927246094}}
