feature:
  critical_cycles:
  - 2
  - 9
  - 99
  interp_dims: 1000
  name: VarianceModelFeatureExtractor
  use_precalculated_qdlin: true
feature_transformation:
  name: ZScoreDataTransformation
label:
  name: RULLabelAnnotator
label_transformation:
  name: SequentialDataTransformation
  transformations:
  - name: LogScaleDataTransformation
  - name: ZScoreDataTransformation
model:
  name: LinearRegressionRULPredictor
train_test_split:
  cell_data_path: data/processed/HUST/final_5_12
  name: HUSTTrainTestSplitter
